name: Create Signing Key

on:
  workflow_dispatch:

jobs:
  create-key:
    runs-on: ubuntu-latest

    steps:
      - name: Create keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore element.jks \
            -storepass ElementKey123! \
            -keypass ElementKey123! \
            -alias element \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Element, OU=Android, O=Element, L=London, ST=London, C=GB"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: element-signing-key
          path: element.jks
